### ISSUE TITLE
Minor Error. Amp Code

### ISSUE THREAD

**Issue by kalverra** [Hanselmus/prj-rev-bwfs-dasmoto#1]
https://github.com/Hanselmus/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L9

& is a special character in HTML, check here. http://rabbit.eng.miami.edu/info/htmlchars.html

**Comment by Hanselmus** [comment]
Then Codecademy is a bit tricky ;-) If we want to reproduce the website like it is on the design template we had to use "&", but that was not mentioned in our lessons before
