### ISSUE TITLE
Simplify. CSS organization

### ISSUE THREAD

**Issue by kalverra** [Hanselmus/prj-rev-bwfs-dasmoto#5]
https://github.com/Hanselmus/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/dasmoto.css#L3-L4

Use spacing to help organize your CSS. https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines

**Comment by Hanselmus** [comment]
Thx, useful reading
