### ISSUE TITLE
Summary.

### ISSUE THREAD

**Issue by kalverra** [Hanselmus/prj-rev-bwfs-dasmoto#6]
**Grade**: Satisfactory

**Summary**:
Overall your code functions well, but make sure to pay attention to how it looks as well. Implementing good coding practices helps others and you read and work on your code much easier. See my comments on spacing and general organization. Otherwise, keep it up.

Make sure to check out my link on & codes, they're very important in HTML for representing special characters.

**Comment by Hanselmus** [comment]
Thank you very much reviewing and commenting my work.
